name: pelican
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - pelican
  - markdown<3
  - typogrify
  - invoke
  - webassets
  - cssmin
  - libsass
  - pyscss
  - ply
  - coconut
  - beautifulsoup4
  - pyparsing==2.2.0
  - pip:
      - slimit
      - HTMLParser
