[tool.poetry]
name = "blog"
version = "0.1.0"
description = "Hyperreals *R"
authors = ["chemacortes <devxtrem@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pelican = "^4.2.0"
webassets = "^2.0"
markdown = "^3.2.2"
typogrify = "^2.0.7"
pyscss2 = "^2.0.0"
cssmin = "^0.2.0"
ghp-import2 = "^1.0.1"
slimit = "^0.8.1"


[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
