[tool.poetry]
name        = "blog"
version     = "0.2.0"
description = "Hyperreals *R"
authors     = ["chemacortes <devxtrem@gmail.com>"]

[tool.poetry.dependencies]
python      = "^3.8"
pelican     = "^4.5.0"
webassets   = "^2.0"
markdown    = "^3.3.0"
typogrify   = "^2.0.7"
cssmin      = "^0.2.0"
ghp-import2 = "^1.0.1"
slimit      = "^0.8.1"
pyscss      = "^1.3.7"
Jinja2      = "^2.11.2"
mdx-include = "^1.4.1"

[tool.poetry.dev-dependencies]
pylama         = "^7.7.1"
black          = { version = "^20.8b1", allow-prereleases = true }
python-slugify = "^4.0.1"
invoke         = "^1.5.0"

[build-system]
requires      = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
